server:  
  port: 8080

spring:  
  application:
    name: Admin-REST

eureka:  
  client:
    serviceUrl:
      defaultZone: http://eureka-nonextant-ad.cfapps.io/eureka/
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80